### PR TITLE
Allows users to specify that certain colors of pixels should be ignor…

### PR DESCRIPTION
**Pull request by adrichem**
Allows users to specify that certain colors of pixels should be ignored during the compare process.

### CODE REVIEW

**Comment by mourner** [comment]
Interesting! What's your use case for this?

**Comment by adrichem** [comment]
My testautomation takes screenshots of our system and compares them against well known baselines. However some area's of the page will be different every time the test executes. These area's have been masked in the baselines with some color and may not contribute to deciding that the images are different.

**Comment by mourner** [comment]
I feel like picking a specific color as an indication of ignore zones is a bit weird... Wouldn't it be simpler to mask both input and output that you feed into pixelmatch for the same result?

**Comment by adrichem** [comment]
One of the components in the test infrastructure must make the decision “should I compare this pixel yes or no?” So, we must choose where to put that responsibility:

1. The caller of the library. In my case probably a NodeJS/express combination in a docker container.
2. The library itself.

I prefer the library because it knows how to decode image files and read pixels. I don’t want other components to have to worry about that. The only thing they should be responsible for is:

1. Sending the baseline image and the actual runtime image to whatever component does the image comparison
2. Telling that component what the ignore color is for that image.

**Comment by adrichem** [comment]
On 2nd thought, I think you have a good point. Lets close the PR. Who ever decodes the image stream into a bitmap representation is the best component to implement the masking. and thats not the library :)

**Comment by mourner** [comment]
Thanks for the PR nevertheless!

**Pull request closed without merging**
